### ISSUE TITLE
Can you also provide a plain js-file

### ISSUE THREAD

**Issue by hamburger123456** [rossrobino/drab#14]
Nice Tool,
but I do not have any clue from Typescript, and dont wont to run all this compilers.
Can you simple provide a compiled javascript file?
Thanks in advance.
joe
This is of course not an issue .. I didn't get the pull-request from github to run ...

**Comment by rossrobino** [comment]
Hi @hamburger123456 

Thanks for the interest in the library. The code is written in typescript but it is transpiled to JavaScript before it is published. If you have [installed via npm](https://drab.robino.dev/getting-started/#install) you can find the JavaScript code for each element in your node_modules directory (ignore the d.ts files).

If you just want the js to copy and paste into your project without installing, you can find it on [npm](https://www.npmjs.com/package/drab?activeTab=code). The .iife versions contain all of the code required to run each component. 

Let me know if this is what you are looking for or if I can provide another version.

**Comment by hamburger123456** [comment]
Thx ross for your answer.
an uncompressed js-version would be great.
where #t=new AbortController;
is like the codeorigin  #listenerController = new AbortController();

**Comment by rossrobino** [comment]
The ESM version now uses `tsc` to compile instead of tsup. You can find the uncompressed version on [npm](https://www.npmjs.com/package/drab?activeTab=code), and when installing the package. Make sure you are using version >5.0.2.

IIFE is still minified.

Thanks for reporting! I think this will make it easier to debug issues when using the package.
